name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar kubectl e Helm
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Validar arquivos YAML do Kubernetes
        run: |
          kubectl apply --dry-run=client -f manifests/

      - name: Testar Helm Charts
        run: |
          helm lint manifests/prometheus-stack.yaml
